### ISSUE TITLE
make users aware of the data licence

### ISSUE THREAD

**Issue by mtmail** [shayonj/emergency_number#2]
The emergency number data is licensed under OdBL. That has some restrictions on usage, the most important what happens if you merge it with other data. It's best to mention OdBL in the README.

**Comment by shayonj** [comment]
Yes definitely. I will mention OdBL from here https://github.com/EmergencyNumberAPI/data/blob/master/LICENSE.md and have the gem as MIT. Thanks!

**Comment by shayonj** [comment]
Fixed at https://github.com/shayonj/emergency_number/commit/7d7cddb26ff68ff0309110450692a8833ac92546
